sonar.organization=samuelyepesdev
sonar.projectKey=samuelyepesdev_Gastroflow

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,dist-electron*/**,.local-desktop/**,public/vendor/**,**/*.min.js
sonar.tests=tests
sonar.test.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
